# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainUi2.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_widget(object):
    def setupUi(self, widget):
        widget.setObjectName("widget")
        widget.resize(1180, 828)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(widget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(widget)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.pushButton_1 = QtWidgets.QPushButton(widget)
        self.pushButton_1.setStyleSheet("font: 14pt \"Agency FB\";")
        self.pushButton_1.setDefault(False)
        self.pushButton_1.setObjectName("pushButton_1")
        self.verticalLayout.addWidget(self.pushButton_1)
        self.textEdit = QtWidgets.QTextEdit(widget)
        self.textEdit.setObjectName("textEdit")
        self.verticalLayout.addWidget(self.textEdit)
        self.pushButton_2 = QtWidgets.QPushButton(widget)
        self.pushButton_2.setStyleSheet("font: 14pt \"Agency FB\";")
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalLayout.addWidget(self.pushButton_2)
        self.pushButton_3 = QtWidgets.QPushButton(widget)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setStyleSheet("font: 14pt \"Agency FB\";")
        self.pushButton_3.setObjectName("pushButton_3")
        self.verticalLayout.addWidget(self.pushButton_3)
        self.pushButton_4 = QtWidgets.QPushButton(widget)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setStyleSheet("font: 14pt \"Agency FB\";")
        self.pushButton_4.setObjectName("pushButton_4")
        self.verticalLayout.addWidget(self.pushButton_4)
        self.pushButton_5 = QtWidgets.QPushButton(widget)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.pushButton_5.setFont(font)
        self.pushButton_5.setStyleSheet("font: 14pt \"Agency FB\";")
        self.pushButton_5.setObjectName("pushButton_5")
        self.verticalLayout.addWidget(self.pushButton_5)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.label_3 = QtWidgets.QLabel(widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setMaximumSize(QtCore.QSize(1300, 900))
        self.label_3.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3)
        self.verticalLayout_2.addLayout(self.horizontalLayout)

        self.retranslateUi(widget)
        QtCore.QMetaObject.connectSlotsByName(widget)

    def retranslateUi(self, widget):
        _translate = QtCore.QCoreApplication.translate
        widget.setWindowTitle(_translate("widget", "Form"))
        self.label.setText(_translate("widget", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:48pt;\">行人检测系统</span></p></body></html>"))
        self.pushButton_1.setWhatsThis(_translate("widget", "<html><head/><body><p><span style=\" font-size:26pt;\">视频获取</span></p></body></html>"))
        self.pushButton_1.setText(_translate("widget", "视频获取"))
        self.textEdit.setPlaceholderText(_translate("widget", "视频路径"))
        self.pushButton_2.setWhatsThis(_translate("widget", "<html><head/><body><p><span style=\" font-size:26pt;\">视频获取</span></p></body></html>"))
        self.pushButton_2.setText(_translate("widget", "预处理"))
        self.pushButton_3.setWhatsThis(_translate("widget", "<html><head/><body><p><span style=\" font-size:26pt;\">视频获取</span></p></body></html>"))
        self.pushButton_3.setText(_translate("widget", "预处理结果展示"))
        self.pushButton_4.setWhatsThis(_translate("widget", "<html><head/><body><p><span style=\" font-size:26pt;\">视频获取</span></p></body></html>"))
        self.pushButton_4.setText(_translate("widget", "运动区域检测结果展示"))
        self.pushButton_5.setWhatsThis(_translate("widget", "<html><head/><body><p><span style=\" font-size:26pt;\">视频获取</span></p></body></html>"))
        self.pushButton_5.setText(_translate("widget", "行人检测结果展示"))
        self.label_3.setText(_translate("widget", "  图像/视频显示"))
